
export const PATH = {
    GFS_PATH:'/:cartCode/gfs/stores?searchKeyword=:postalCode',

    GUEST_DELIVERY_MODE:'/users/anonymous/carts/:cartId/deliverymode?deliveryModeId=standard-gross',
    DELIVERY_MODE_PATH:'/deliverymode?deliveryModeId=standard-gross',
    DELIVERY_METHOD_TO_CART:'/users/:email/carts/:cartCode/selectDeliveryMethod?deliveryCode=:deliverycode',
    GUEST_DELIVERY_METHOD_TO_CART:'/users/anonymous/carts/:cartCode/selectDeliveryMethod?deliveryCode=:deliverycode',
    DELIVERY_METHOD:'/users/:email/carts/:cartCode/DeliveryMethods',
    GUEST_DELIVERY_METHOD:'/users/anonymous/carts/:cartCode/DeliveryMethods',
    
    DELIVERY_NAMED_DAY_SERVICE:'/users/:email/carts/:cartCode/SetNamedDeliveryModeToCart?deliveryCode=:deliveryCode',
    SET_DELIVERY_NAMED_DAY_SERVICE:'/users/anonymous/carts/:cartCode/SetNamedDeliveryModeToCart?deliveryCode=:deliveryCode',

    DELIVERY_SERVICE:'/users/:email/carts/:cartCode/NamedDeliveryServices?baseSiteId=:baseSiteId',
    GUEST_DELIVERY_SERVICE:'/users/anonymous/carts/:cartCode/NamedDeliveryServices?baseSiteId=:baseSiteId',


    GET_INTERNATIONAL_DELIVERY_METHOD:'/users/:email/carts/:cartCode/InternationalDelivery?countryCode=:countryCode',
    GUEST_GET_INTERNATIONAL_DELIVERY_METHOD:'/users/anonymous/carts/:cartCode/InternationalDelivery?countryCode=:countryCode',

    SET_INTERNATIONAL_DELIVERY_METHOD:'/users/:email/carts/:cartCode/SetIntDeliveryModeToCart?countryCode=:countryCode&deliveryCode=International-Delivery',
    GUEST_SET_INTERNATIONAL_DELIVERY_METHOD:'/users/anonymous/carts/:cartCode/SetIntDeliveryModeToCart?countryCode=:countryCode&deliveryCode=International-Delivery',

    FIND_POSTCODE:'https://services.postcodeanywhere.co.uk/PostcodeAnywhere/Interactive/FindByPostcode/v1.00/json3.ws?&Postcode=:postCode&Key=PZ52-UH91-BW19-BT37', 
    POSTAL_ADDRESS:'https://services.postcodeanywhere.co.uk/PostcodeAnywhere/Interactive/RetrieveById/v1.20/json3.ws?&Key=PZ52-UH91-BW19-BT37&Id=:postCode',
  
    CREATE_ADDRESS:'/users/:email/addresses',
    UPDATE_ADDRESS:'/users/:email/addresses/:addressId',
    SHIPPING_ADDRESS:'/user/:email/carts/:cartCode/addresses/delivery',
    GUEST_SHIPPING_ADDRESS:'/users/anonymous/carts/:cartId/addresses/delivery',
    CONFIRM_ADDRESS:'/users/:email/carts/:cartCode/confirmAddress?addressCode=:addressId',
   
    PROFILE:'/users/:email',

    REG_SPLIT_PAYMENT:'/users/:email/carts/:cartCode/giftcard/splitpayment?firstName=:firstName&lastName=:lastName&givexCardNumber=:givexCardNumber&givexPinNumber=:givexPinNumber&amount=:amount',
    GUEST_SPLIT_PAYMENT:'/users/anonymous/carts/:cartCode/giftcard/splitpayment?firstName=:firstName&lastName=:lastName&givexCardNumber=:givexCardNumber&givexPinNumber=:givexPinNumber&amount=:amount',
  
    PRODUCT_DETAIL:'/products/:productCode',
    CATEGORY_PRODUCTS:'/products/:categoryCode&pageSize=:pageSize&fields=FULL&sort=name-asc',
    CATEGORY_SEARCH_PRODUCTS:'/products/search?query=:searchValue&pageSize=:pageSize&fields=FULL',
    CATEGORY_SEARCH_RESULTS:'/products/search?query=:searchValue',

  


    REGISTER_CART:'/users/:email/carts',
    REMOVE_FAVOURITE:'/users/:email/wishlist/remove/?code=:productCode',
    GUEST_ADD_TO_BASKET:'/users/anonymous/carts/:cartCode/entries',
    ADD_TO_BASKET:'/users/:email/carts/:cartCode/entries',
   

    FAVOURITES:'/users/:email/wishlist/retrieve',
    ADD_FAVOURITES:'/users/:email/wishlist/add?code=:code',
   
    ORDER_HISTORY_DETAILS:'/users/:email/orders/:orderCode',
    ORDER_HISTORY_PATH:'/users/:email/orders',
   
    GIFT_BOX:'/users/:email/carts/:cartCode/giftBox',
    GIFT_CARD:'/users/:email/carts/:cartCode/giftcard',
    GUEST_GIFT_CARD:'/users/anonymous/carts/:cartCode/giftcard ',
    CHECK_BALANCE:'/checkbalance',

   

   
    REG_GIVEX_PAYMENT_DETAIL:'/users/:email/carts/:cartCode/paymentdetails',
    GUEST_GIVEX_PAYMENT_DETAIL:'/users/anonymous/carts/:cartCode/paymentdetails',

    
   

    ORDERCONFIRMATION:'/orders/:orderId',
    GUEST_ORDERCONFIRMATION:'/users/anonymous/orders?cartId=:cartId&securityCode=:cvv',
   


    GUEST_DEBIT_PAYMENT:'/users/anonymous/carts/:cartId/payment',
    REG_DEBIT_PAYMENT:'/users/:email/carts/:cartCode/payment',

    GUEST_CART_DETAIL:'/users/anonymous/carts/:cartCode/?fields=FULL',
    USER_CARTDETAILS:'/users/:email/carts/:cartID/?fields=FULL',
    MERGE_CART:'/users/:email/carts?oldCartId=:oldCartId&toMergeCartGuid=:newCartId',
   
 
   
    SITE_AUTENTICATION:'https://api.cxur-kaocorpor1-d1-public.model-t.cc.commerce.ondemand.com/authorizationserver/oauth/token?client_id=clientcq&client_secret=password&grant_type=password&username=:uid&password=:password&siteID=:siteId',
   
    
   
  
    CATEGORY_PATH:'/products/serach?query=&',
    PRODUCT_PATH:'/products',  
    PRODUCT_DATA_PATH:'/products/',
    SAVED_CARDS:'/users/:email/paymentdetails',
    
    catalog:'/catalogs',
   
    CART_TOKEN_PATH:'https://api.cxur-kaocorpor1-d1-public.model-t.cc.commerce.ondemand.com/authorizationserver/oauth/token?client_id=clientcq&client_secret=password&grant_type=client_credentials',
    CART_PATH:'/users/anonymous/carts',
    CREATE_USER_PATH:'/users',
    ANANONYMOUSCART:'/users/anonymous/carts',
  };

 export const SERVER_PATHS = {
  DEV: 'https://api.cxur-kaocorpor1-d1-public.model-t.cc.commerce.ondemand.com/kaowebservices/v2/'
 
 }; 


 export const countries=[
  {name: "Åland Islands", isocode: "AX"},
  {name: "Albania", isocode: "AL"},
  {name: "Algeria", isocode: "DZ"},
  {name: "American Samoa", isocode: "AS"},
  {name: "AndorrA", isocode: "AD"},
  {name: "Angola", isocode: "AO"},
  {name: "Anguilla", isocode: "AI"},
  {name: "Antarctica", isocode: "AQ"},
  {name: "Antigua and Barbuda", isocode: "AG"},
  {name: "Argentina", isocode: "AR"},
  {name: "Armenia", isocode: "AM"},
  {name: "Aruba", isocode: "AW"},
  {name: "Australia", isocode: "AU"},
  {name: "Austria", isocode: "AT"},
  {name: "Azerbaijan", isocode: "AZ"},
  {name: "Bahamas", isocode: "BS"},
  {name: "Bahrain", isocode: "BH"},
  {name: "Bangladesh", isocode: "BD"},
  {name: "Barbados", isocode: "BB"},
  {name: "Belarus", isocode: "BY"},
  {name: "Belgium", isocode: "BE"},
  {name: "Belize", isocode: "BZ"},
  {name: "Benin", isocode: "BJ"},
  {name: "Bermuda", isocode: "BM"},
  {name: "Bhutan", isocode: "BT"},
  {name: "Bolivia", isocode: "BO"},
  {name: "Bosnia and Herzegovina", isocode: "BA"},
  {name: "Botswana", isocode: "BW"},
  {name: "Bouvet Island", isocode: "BV"},
  {name: "Brazil", isocode: "BR"},
  {name: "British Indian Ocean Territory", isocode: "IO"},
  {name: "Brunei Darussalam", isocode: "BN"},
  {name: "Bulgaria", isocode: "BG"},
  {name: "Burkina Faso", isocode: "BF"},
  {name: "Burundi", isocode: "BI"},
  {name: "Cambodia", isocode: "KH"},
  {name: "Cameroon", isocode: "CM"},
  {name: "Canada", isocode: "CA"},
  {name: "Cape Verde", isocode: "CV"},
  {name: "Cayman Islands", isocode: "KY"},
  {name: "Central African Republic", isocode: "CF"},
  {name: "Chad", isocode: "TD"},
  {name: "Chile", isocode: "CL"},
  {name: "China", isocode: "CN"},
  {name: "Christmas Island", isocode: "CX"},
  {name: "Cocos (Keeling) Islands", isocode: "CC"},
  {name: "Colombia", isocode: "CO"},
  {name: "Comoros", isocode: "KM"},
  {name: "Congo", isocode: "CG"},
  {name: "Congo, The Democratic Republic of the", isocode: "CD"},
  {name: "Cook Islands", isocode: "CK"},
  {name: "Costa Rica", isocode: "CR"},
  {name: "Cote D'Ivoire", isocode: "CI"},
  {name: "Croatia", isocode: "HR"},
  {name: "Cuba", isocode: "CU"},
  {name: "Cyprus", isocode: "CY"},
  {name: "Czech Republic", isocode: "CZ"},
  {name: "Denmark", isocode: "DK"},
  {name: "Djibouti", isocode: "DJ"},
  {name: "Dominica", isocode: "DM"},
  {name: "Dominican Republic", isocode: "DO"},
  {name: "Ecuador", isocode: "EC"},
  {name: "Egypt", isocode: "EG"},
  {name: "El Salvador", isocode: "SV"},
  {name: "Equatorial Guinea", isocode: "GQ"},
  {name: "Eritrea", isocode: "ER"},
  {name: "Estonia", isocode: "EE"},
  {name: "Ethiopia", isocode: "ET"},
  {name: "Falkland Islands (Malvinas)", isocode: "FK"},
  {name: "Faroe Islands", isocode: "FO"},
  {name: "Fiji", isocode: "FJ"},
  {name: "Finland", isocode: "FI"},
  {name: "France", isocode: "FR"},
  {name: "French Guiana", isocode: "GF"},
  {name: "French Polynesia", isocode: "PF"},
  {name: "French Southern Territories", isocode: "TF"},
  {name: "Gabon", isocode: "GA"},
  {name: "Gambia", isocode: "GM"},
  {name: "Georgia", isocode: "GE"},
  {name: "Germany", isocode: "DE"},
  {name: "Ghana", isocode: "GH"},
  {name: "Gibraltar", isocode: "GI"},
  {name: "Greece", isocode: "GR"},
  {name: "Greenland", isocode: "GL"},
  {name: "Grenada", isocode: "GD"},
  {name: "Guadeloupe", isocode: "GP"},
  {name: "Guam", isocode: "GU"},
  {name: "Guatemala", isocode: "GT"},
  {name: "Guernsey", isocode: "GG"},
  {name: "Guinea", isocode: "GN"},
  {name: "Guinea-Bissau", isocode: "GW"},
  {name: "Guyana", isocode: "GY"},
  {name: "Haiti", isocode: "HT"},
  {name: "Heard Island and Mcdonald Islands", isocode: "HM"},
  {name: "Holy See (Vatican City State)", isocode: "VA"},
  {name: "Honduras", isocode: "HN"},
  {name: "Hong Kong", isocode: "HK"},
  {name: "Hungary", isocode: "HU"},
  {name: "Iceland", isocode: "IS"},
  {name: "India", isocode: "IN"},
  {name: "Indonesia", isocode: "ID"},
  {name: "Iran, Islamic Republic Of", isocode: "IR"},
  {name: "Iraq", isocode: "IQ"},
  {name: "Ireland", isocode: "IE"},
  {name: "Isle of Man", isocode: "IM"},
  {name: "Israel", isocode: "IL"},
  {name: "Italy", isocode: "IT"},
  {name: "Jamaica", isocode: "JM"},
  {name: "Japan", isocode: "JP"},
  {name: "Jersey", isocode: "JE"},
  {name: "Jordan", isocode: "JO"},
  {name: "Kazakhstan", isocode: "KZ"},
  {name: "Kenya", isocode: "KE"},
  {name: "Kiribati", isocode: "KI"},
  {name: "Korea, Democratic People'S Republic of", isocode: "KP"},
  {name: "Korea, Republic of", isocode: "KR"},
  {name: "Kuwait", isocode: "KW"},
  {name: "Kyrgyzstan", isocode: "KG"},
  {name: "Lao People'S Democratic Republic", isocode: "LA"},
  {name: "Latvia", isocode: "LV"},
  {name: "Lebanon", isocode: "LB"},
  {name: "Lesotho", isocode: "LS"},
  {name: "Liberia", isocode: "LR"},
  {name: "Libyan Arab Jamahiriya", isocode: "LY"},
  {name: "Liechtenstein", isocode: "LI"},
  {name: "Lithuania", isocode: "LT"},
  {name: "Luxembourg", isocode: "LU"},
  {name: "Macao", isocode: "MO"},
  {name: "Macedonia, The Former Yugoslav Republic of", isocode: "MK"},
  {name: "Madagascar", isocode: "MG"},
  {name: "Malawi", isocode: "MW"},
  {name: "Malaysia", isocode: "MY"},
  {name: "Maldives", isocode: "MV"},
  {name: "Mali", isocode: "ML"},
  {name: "Malta", isocode: "MT"},
  {name: "Marshall Islands", isocode: "MH"},
  {name: "Martinique", isocode: "MQ"},
  {name: "Mauritania", isocode: "MR"},
  {name: "Mauritius", isocode: "MU"},
  {name: "Mayotte", isocode: "YT"},
  {name: "Mexico", isocode: "MX"},
  {name: "Micronesia, Federated States of", isocode: "FM"},
  {name: "Moldova, Republic of", isocode: "MD"},
  {name: "Monaco", isocode: "MC"},
  {name: "Mongolia", isocode: "MN"},
  {name: "Montserrat", isocode: "MS"},
  {name: "Morocco", isocode: "MA"},
  {name: "Mozambique", isocode: "MZ"},
  {name: "Myanmar", isocode: "MM"},
  {name: "Namibia", isocode: "NA"},
  {name: "Nauru", isocode: "NR"},
  {name: "Nepal", isocode: "NP"},
  {name: "Netherlands", isocode: "NL"},
  {name: "Netherlands Antilles", isocode: "AN"},
  {name: "New Caledonia", isocode: "NC"},
  {name: "New Zealand", isocode: "NZ"},
  {name: "Nicaragua", isocode: "NI"},
  {name: "Niger", isocode: "NE"},
  {name: "Nigeria", isocode: "NG"},
  {name: "Niue", isocode: "NU"},
  {name: "Norfolk Island", isocode: "NF"},
  {name: "Northern Mariana Islands", isocode: "MP"},
  {name: "Norway", isocode: "NO"},
  {name: "Oman", isocode: "OM"},
  {name: "Pakistan", isocode: "PK"},
  {name: "Palau", isocode: "PW"},
  {name: "Palestinian Territory, Occupied", isocode: "PS"},
  {name: "Panama", isocode: "PA"},
  {name: "Papua New Guinea", isocode: "PG"},
  {name: "Paraguay", isocode: "PY"},
  {name: "Peru", isocode: "PE"},
  {name: "Philippines", isocode: "PH"},
  {name: "Pitcairn", isocode: "PN"},
  {name: "Poland", isocode: "PL"},
  {name: "Portugal", isocode: "PT"},
  {name: "Puerto Rico", isocode: "PR"},
  {name: "Qatar", isocode: "QA"},
  {name: "Reunion", isocode: "RE"},
  {name: "Romania", isocode: "RO"},
  {name: "Russian Federation", isocode: "RU"},
  {name: "RWANDA", isocode: "RW"},
  {name: "Saint Helena", isocode: "SH"},
  {name: "Saint Kitts and Nevis", isocode: "KN"},
  {name: "Saint Lucia", isocode: "LC"},
  {name: "Saint Pierre and Miquelon", isocode: "PM"},
  {name: "Saint Vincent and the Grenadines", isocode: "VC"},
  {name: "Samoa", isocode: "WS"},
  {name: "San Marino", isocode: "SM"},
  {name: "Sao Tome and Principe", isocode: "ST"},
  {name: "Saudi Arabia", isocode: "SA"},
  {name: "Senegal", isocode: "SN"},
  {name: "Serbia and Montenegro", isocode: "CS"},
  {name: "Seychelles", isocode: "SC"},
  {name: "Sierra Leone", isocode: "SL"},
  {name: "Singapore", isocode: "SG"},
  {name: "Slovakia", isocode: "SK"},
  {name: "Slovenia", isocode: "SI"},
  {name: "Solomon Islands", isocode: "SB"},
  {name: "Somalia", isocode: "SO"},
  {name: "South Africa", isocode: "ZA"},
  {name: "South Georgia and the South Sandwich Islands", isocode: "GS"},
  {name: "Spain", isocode: "ES"},
  {name: "Sri Lanka", isocode: "LK"},
  {name: "Sudan", isocode: "SD"},
  {name: "Suriname", isocode: "SR"},
  {name: "Svalbard and Jan Mayen", isocode: "SJ"},
  {name: "Swaziland", isocode: "SZ"},
  {name: "Sweden", isocode: "SE"},
  {name: "Switzerland", isocode: "CH"},
  {name: "Syrian Arab Republic", isocode: "SY"},
  {name: "Taiwan, Province of China", isocode: "TW"},
  {name: "Tajikistan", isocode: "TJ"},
  {name: "Tanzania, United Republic of", isocode: "TZ"},
  {name: "Thailand", isocode: "TH"},
  {name: "Timor-Leste", isocode: "TL"},
  {name: "Togo", isocode: "TG"},
  {name: "Tokelau", isocode: "TK"},
  {name: "Tonga", isocode: "TO"},
  {name: "Trinidad and Tobago", isocode: "TT"},
  {name: "Tunisia", isocode: "TN"},
  {name: "Turkey", isocode: "TR"},
  {name: "Turkmenistan", isocode: "TM"},
  {name: "Turks and Caicos Islands", isocode: "TC"},
  {name: "Tuvalu", isocode: "TV"},
  {name: "Uganda", isocode: "UG"},
  {name: "Ukraine", isocode: "UA"},
  {name: "United Arab Emirates", isocode: "AE"},
  {name: "United Kingdom", isocode: "GB"},
  {name: "United States", isocode: "US"},
  {name: "United States Minor Outlying Islands", isocode: "UM"},
  {name: "Uruguay", isocode: "UY"},
  {name: "Uzbekistan", isocode: "UZ"},
  {name: "Vanuatu", isocode: "VU"},
  {name: "Venezuela", isocode: "VE"},
  {name: "Viet Nam", isocode: "VN"},
  {name: "Virgin Islands, British", isocode: "VG"},
  {name: "Virgin Islands, U.S.", isocode: "VI"},
  {name: "Wallis and Futuna", isocode: "WF"},
  {name: "Western Sahara", isocode: "EH"},
  {name: "Yemen", isocode: "YE"},
  {name: "Zambia", isocode: "ZM"},
  {name: "Zimbabwe", isocode: "ZW"}
  ];
 
